### ISSUE TITLE
Streaming Emotiv data via CyKit3

### ISSUE THREAD

**Issue by teknomage** [CymatiCorp/CyKit#19]
Hello Warren, it's been a couple of years since I last reached out to you about a lagging issue that I was experiencing with the previous CyKitv2 (see the original thread here: [(https://github.com/CymatiCorp/CyKITv2/issues/9)] )
Well, I'm glad to say that after I upgraded to this newer CyKit version with Python 3.4 (I couldn't get it to work with Python's higher versions), that lag in the data display has reduced significantly... and I love the updated interface too! :)

Now, for the query I have in mind: it's not really an issue but I'd like to know how I could stream the live incoming EEG data from Emotiv via CyKit into a python program. I understand it's possible to stream to OpenVibe (and even Matlab?), but all I need is a simple python listener script to receive the data. I'm not an expert in python, so if you could provide me with an example snippet or point me in the right direction, that would be most appreciated!

Oh, and it would be nice if you could include a short note on how to use the Calibration feature in this updated version.

Thanks for all the great work you've done here and for keeping this CyKit project alive, kudos to ya!!

**Comment by warrenarea** [comment]
Added "Examples" to the repository you can take a look at
for how to retrieve the data directly from the CyKIT engine.

I have plans to improve upon this system, so this is just the 
current available method.

**Comment by teknomage** [comment]
That's great, Warren! Thank you so much for putting this up!
