### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Emotiv' 

### ISSUE THREAD

**Issue by winimanthas** [CymatiCorp/CyKit#2]
Hi,
I get this error when running the example.py file.  I have installed all the require packges in python and have connected the USB dongle and it is paired. but I still receive this error. Quick reply is very much appriciated

Traceback (most recent call last):
  File "example.py", line 10, in <module>
    headset = emotiv.Emotiv(False, False)
AttributeError: 'module' object has no attribute 'Emotiv'

**Comment by warrenarea** [comment]
Typically this error occurs if the headset is not connected and paired.
Did you ever get it to work?
