### ISSUE TITLE
About Epoc X

### ISSUE THREAD

**Issue by batulaiko** [CymatiCorp/CyKit#26]
How Can I connect Epoc X via Cykit? What is the Key Number of it?

Have a nice day.

**Comment by yxbu** [comment]
i have the same problem do you find any solution???

**Comment by batulaiko** [comment]
> i have the same problem do you find any solution???
I asked EMOTIV itself. YOu choose 16-bit mode in EMOTIV APP. Then ,in CyKit, KEy is 6 I guess. I get data from it but the data is not correct in my opinion.

**Comment by warrenarea** [comment]
Check with me on discord.  Discord link on this repository.

**Comment by dongchaoqun95** [comment]
May I ask if Epoc X can be supported now? I have encountered the same problem, the process can run smoothly, but the waveform is not very correct

**Comment by dongchaoqun95** [comment]
@batulaiko @yxbu @warrenarea May I ask if Epoc X can be supported now? I have encountered the same problem, the process can run smoothly, but the waveform is not very correct
