### ISSUE TITLE
why i can't see the signals in the html?

### ISSUE THREAD

**Issue by JolyneOY** [CymatiCorp/CyKit#27]
I tried to connect epoc flex, but failed. 
Then I tried epoc insight, it shows that the status is connected, the controller id insight, but i can't see the signals.
I entered the following in CMD：
CyKIT.py 127.0.0.1 5151 4 info+confirm

I tried 12991, it worked. But when I tried to  connect to openvibe, the signals disappeared.
I entered the following in CMD：
\CyKIT.py 127.0.0.1 5151 4 openvibe+generic+nocounter+noheader+nobattery+ovdelay:100+float+ovsamples:004

Could you help me find out what's the problem? Thank you very much!!!

**Comment by Solannae** [comment]
I am facing the same issue. I remember it working properly 3 weeks ago, when I first used cykit.
Data is properly extracted when using noweb, however when connecting the web interface to cykit, every sensor turns to green but no data is displayed at all.

Running with the following options:
CyKit.py 127.0.0.1 54123 7

**Comment by JolyneOY** [comment]
> I am facing the same issue. I remember it working properly 3 weeks ago, when I first used cykit.
> Data is properly extracted when using noweb, however when connecting the web interface to cykit, every sensor turns to green but no data is displayed at all.
> 
> Running with the following options:
> CyKit.py 127.0.0.1 54123 7

Did you connect to openvibe 3 weeks ago? I can't even find a EPOC driver in openvibe acquisition server...How should I do to install it?

**Comment by warrenarea** [comment]
its a signal averaging gltich. try alternating the Format values on the left side of the webpage.

Flex is not yet supported, but work has been done with it. may check out our discord. (link on cykit page)

**Comment by JolyneOY** [comment]
> its a signal averaging gltich. try alternating the Format values on the left side of the webpage.
> 
> Flex is not yet supported, but work has been done with it. may check out our discord. (link on cykit page)

THANK YOU, warren!!! I made it!!!
I still couldn't see signals in the web when I try the +openvibe command in the cmd, but when I open the openvibe designer and used the siganl display, I could see the 4 channels' signals!!!
Looking forward to your update on Flex!!!!
Have a nice day  ; )
