### ISSUE TITLE
local variable 'uid' referenced before assignment

### ISSUE THREAD

**Issue by spacepoolnoodle** [CymatiCorp/CyKit#28]
The datastream works pretty great, but after roughly 30 seconds of running, I get the following error:

```
Exception in thread ioThread:
Traceback (most recent call last):
  File "C:\Python377\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Python377\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File ".\CyWebSocket.py", line 272, in run
    self.onData(true_data)
  File ".\CyWebSocket.py", line 300, in onData
    hashStr = hashlib.new("md5",(str(uid)+self.signKey).encode('utf-8')).hexdigest()
UnboundLocalError: local variable 'uid' referenced before assignment
```

I am streaming the data to Matlab using this addon: https://www.mathworks.com/matlabcentral/fileexchange/50040-jebej-matlabwebsocket. 

I use a .bat with the following config to start the server:
```
C:\Python377\python.exe .\cyKIT.py 127.0.0.1 5151 4 verbose
```

**Comment by warrenarea** [comment]
Run with no other config options, it defaults to trying to connect to the browser.
UID is a variable relating to that connection.

for 'other' connections that aren't to the CyKIT.html browser setup,  you will want to use the "+generic" configuration option, for a generic socket.  (ie. not a websocket)
