### ISSUE TITLE
Problems starting Cykit after an update 

### ISSUE THREAD

**Issue by CarlosA-Mtz** [CymatiCorp/CyKit#30]
Other times I have used Cykit without problems, but recently I updated the headband and now I cannot start Cykit.

**Comment by warrenarea** [comment]
Updated the AES pycryptodomex binaries for Python 3.10 
so it should now work with the latest Python 3.10.

Also fixed a couple new deprecated functions incurred by 3.9x to 3.10

So far, the issues have mainly been from Python updates.
