### ISSUE TITLE
Cykit doesn't show me the waves

### ISSUE THREAD

**Issue by CarlosA-Mtz** [CymatiCorp/CyKit#31]
I recently updated the headband but Cykit no longer showed me the waves, what can I do to fix it?

**Comment by warrenarea** [comment]
Can you explain a little further?

What type of headset?
How did you update it?  
Has the headset been charged recently?

**Comment by CarlosA-Mtz** [comment]
Hi, my headset is an Emotiv epoc+, and to use the emotiv BCI the emotiv software required an update as well as the headset, since then I got issues with cykit. Regarding  to the battery the headset was fully charged.

**Comment by warrenarea** [comment]
yes, this may be an issue.

The EPOC+ firmware has been updated from 0x625 to 0x626
I have not yet tested out this firmware update to see what was changed.

Have you tried the 2 different keys for 128hz and 256hz?  
I think its keymodel 4, for 128hz
and keymodel 6 for 256hz

python.exe .\cykit.py 127.0.0.1 54123 4 outputdata+noweb+pywinusb
python.exe .\cykit.py 127.0.0.1 54123 6 outputdata+noweb+pywinusb

and if you could give a screenshot of your results, to see what we're working with?

**Comment by warrenarea** [comment]
so i had some time to look over the code,
and i think there were some changes to the format, 
but i think they should be easy to fix.


also, to change the "device mode" (ie. 128hz to 256hz),  they made some
changes, so i'll have to create code to adjust for that.
