### ISSUE TITLE
Could not open socket

### ISSUE THREAD

**Issue by xinchencai** [CymatiCorp/CyKit#8]
Hi! I face this problem where the command prompt just disappears after i open the Cyos.py file, and when i run it through IDLE, i get this message:

_Usage:  Python.exe stream.py IP Port
Defaulting to localhost:5555
Listening to localhost : 5555
Could not open socket
Windows detected.
Product name Dell KM632 Wireless Keyboard and Mouse
device path \\?\hid#vid_413c&pid_2501&mi_01&col01#7&31e16739&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
instance id HID\VID_413C&PID_2501&MI_01&COL01\7&31E16739&0&0000

Product name Emotiv RAW DATA
device path \\?\hid#vid_1234&pid_ed02&mi_01#8&2902593b&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
instance id HID\VID_1234&PID_ED02&MI_01\8&2902593B&0&0000

Emotiv RAW DATA Found!

Use this device? [Y]es?_ 

I noticed that it says "Could not open socket". Can i check what is this referring to?

**Comment by warrenarea** [comment]
do you have a firewall installed?  That error seems to indicate possibly the socket is in use, or a firewall is blocking it possibly.
