### ISSUE TITLE
The selected device is always 0

### ISSUE THREAD

**Issue by Athif-UoM** [CymatiCorp/CyKit#9]
Hi, I have previously installed cykit and used it with OpenVibe with my windows 7 computer with python 2.7.11. However when I followed the same procedure on another computer with windows 7 and python 2.7.14, I cannot get the device selected to be 1. So when I proceed with that selection I see only the values printed as 0s for all the signal values.

I am attaching a screen capture of the error (top right) of which I cannot understand the cause. I will be much thankful if you could point the correct direction. 

![openvibeerror](https://user-images.githubusercontent.com/26842643/33229456-3d3c2546-d20a-11e7-9cc8-7b33e6e0acf2.png)

**Comment by warrenarea** [comment]
try taking out line 422 and line 423 of CyKIT/emotiv.py

i'll remove it from the code on the repository as well.

See if that works, i think it blocks some devices from being detected.

**Comment by warrenarea** [comment]
This is the lines i removed:
```
if device.vendor_id != 0x21A1 and device.vendor_id != 0xED02:
                    continue
```

**Comment by Athif-UoM** [comment]
Thanks, but following your suggestion to an earlier issue, I tried removing the lines already and it is still not working.

I went through the code and am suspecting if it has something with hidapi. Even if the device named 'Emotiv Raw Data' is found (The last of the three devices printed in cmd). For some  reason it is not selected. That's puzzling for me. 

Would be much appreciative for your opinion on this


-----Original Message-----

**Comment by warrenarea** [comment]
well, for some reason i don't think so....

because hidapi "is" detecting the device exists....

are you sure that the "Emotiv Raw Data" was the device that needs to be used?

you "might" try adding a new entry for 'Receiver Dongle L01' 
its worth a try.... but if it worked for Emotiv Raw Data, then.... i'm not sure.

**Comment by warrenarea** [comment]
try removing the confirmation for the "Emotiv Raw DATA"

or try adding letters around the Emotiv RAW DATA, to see if there is a space or something..

i think if you play around with it, removing stuff and having it print out as much
information as you can, you might find something....

**Comment by Athif-UoM** [comment]
Thanks ! I will get back with what I get after playing around there

**Comment by warrenarea** [comment]
sounds good.

**Comment by warrenarea** [comment]
not really relevant to your connection problem....
but your connection port is different. lol

**Comment by Athif-UoM** [comment]
Pardon me for the ignorance. Could you please explain me on that. It could be the reason as well  (?) :O . Is this the difference? 
![image](https://user-images.githubusercontent.com/26842643/33235751-560ca274-d27a-11e7-8181-a5fd0759f915.png)

**Comment by warrenarea** [comment]
yeah, thats not relevant. 

your issue is your device isn't being added, its obviously found. 

and what you have circled is a localized port, basically a secondary port that windows
is using kind of behind the scenes to establish your connection.  pay no attention to it.

**Comment by Athif-UoM** [comment]
Thanks. I do not have the access to the computer with the problem at the moment. I was trying to recreate the problem using my computer instead and interestingly, uncommenting line 422 and 423 does that exactly. I will update as soon as I get access to the problematic computer.
